benchmark:
  results_dir: results
  analysis_dir: analysis
  tmp_dir: tmp
  done_message: '> Done.'
  submit_log_file: submit.log
  sleep_time: 10 #300

experiments:
  length_cases:
    - {length: 60000, seeds: [42, 42]}
  #  - {length: 90000, seeds: [1, 1]}
  #  - {length: 120000, seeds: [3, 3]}
  #  - {length: 150000, seeds: [5, 5]}
  #  - {length: 180000, seeds: [12, 12]}
  test_cases:
    - {nodes: 1, ntasks: 1, cpu_list: [0], ntasks_per_node: 1, bind_to: core, memory: 4G, repeats_per_job: 2} #20
    - {nodes: 1, ntasks: 2, cpu_list: [0, 2], ntasks_per_node: 2, bind_to: core, memory: 4G, repeats_per_job: 2} #20
    - {nodes: 1, ntasks: 3, cpu_list: [0, 2, 4], ntasks_per_node: 3, bind_to: core, memory: 4G, repeats_per_job: 2} #20
    - {nodes: 2, ntasks: 2, cpu_list: [0], ntasks_per_node: 1, bind_to: core, memory: 4G, repeats_per_job: 2} #20
    - {nodes: 2, ntasks: 4, cpu_list: [0, 2], ntasks_per_node: 2, bind_to: core, memory: 4G, repeats_per_job: 2} #20
    - {nodes: 2, ntasks: 6, cpu_list: [0, 2, 4], ntasks_per_node: 3, bind_to: core, memory: 4G, repeats_per_job: 2} #20
  #  - {nodes: 2, ntasks: 12, cpu_list: [0, 1, 2, 3, 4, 5], ntasks_per_node: 6, bind_to: none, memory: 4G, repeats_per_job: 2}
  #  - {nodes: 1, ntasks: 6, cpu_list: [0, 1, 2, 3, 4, 5], ntasks_per_node: 6, bind_to: none, memory: 4G, repeats_per_job: 2}

makefile:
  path: .
  variables_path: variables.mk

cluster:
  remote_dir: LCS-MPI
  remote_host: nomade-dinf  

release:
  target: lcs-release
  binary: ./build/bin/lcs-release
  repeats: 2 #20
  sleep_time: 10 #180

profile:
  target: lcs-profile
  binary: ./build/bin/lcs-profile
  function: computeBlock
  repeats: 2 #20
  repeats_per_job: 2 #20
  sleep_time: 10 #60
  memory: 4G #---
  length_cases:
    - {length: 60000, seeds: [42, 43]}

amdahl:
  processes: [1, 2, 3, 6, 12]


